# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9dc28543efeaaa7da3ae25c90cb075e5848f1db44e69da32905b237b33f01dc5a8eb81253b6864d3e95aeef549a599e2ccfcb3d9445691279b5fe2d6aea5b07

test:
  secret_key_base: 3b16cad5491a13caa700bfdb0a4273f73fce4d0825751d93c26998d017494284da97ef12946a8486ec9aebfd068d0541ceb421e31c1267590c21838d1c8ebe31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
